name: Hello World Innotech

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
    
jobs:
  greet:
    env:
      MY_NAME: "Rubén Muñoz"
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Listado de archivos antes del checkout"
            echo "by $MY_NAME"
        - uses: actions/checkout@v2
        
