name: Hello World Innotech

on:
  workflow_dispatch:

jobs:
  greet:
    env:
      MY_NAME: "John Doe"
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Listado de archivos antes del checkout"
            echo "by $MY_NAME"
        - run: ls -l
        - uses: actions/checkout@v2
        - run: echo "Listado de archivos DESPUÉS del checkout"
        - run: ls -l
        
