name: Hello World Innotech

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Listado de archivos antes del checkout"
        - run: ls -l
        - uses: actions/checkout@v2
        - run: echo "Listado de archivos DESPUÉS del checkout"
        - run: ls -l
        
